services:
  redis-cache:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - devsprint-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  order:
    build: services/order
    ports:
      - "8000:8000"
    networks:
      - devsprint-network
    depends_on:
      redis-cache:
        condition: service_healthy
      auth:
        condition: service_started

  stock:
    build: services/stock
    ports:
      - "8080:8080"
    networks:
      - devsprint-network
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://devsprint:devsprint@stock-db:5432/stock
    depends_on:
      stock-db:
        condition: service_healthy

  auth:
    image: registry.supertokens.io/supertokens/supertokens-postgresql
    ports:
      - "3567:3567"
    environment:
      - POSTGRESQL_CONNECTION_URI=postgresql://devsprint:devsprint@auth-db:5432/devsprint
      - API_KEYS=the-most-super-secret-key
    networks:
      - devsprint-network
    depends_on:
      auth-db:
        condition: service_healthy

  auth-db:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=devsprint
      - POSTGRES_PASSWORD=devsprint
      - POSTGRES_DB=devsprint
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devsprint -d devsprint"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devsprint-network

  stock-db:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_USER=devsprint
      - POSTGRES_PASSWORD=devsprint
      - POSTGRES_DB=stock
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devsprint -d devsprint"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - devsprint-network

networks:
  devsprint-network: